from app.domain.models import TradingSignal, Direction, SignalStatus, MarketAnalysis

MOCK_SIGNALS = [
    TradingSignal(
        id="sig_xau_001",
        symbol="XAU/USD",
        direction=Direction.BUY,
        timeframe="M15",
        entry_price=2384.20,
        stop_loss=2378.80,
        take_profit_1=2392.00,
        take_profit_2=2401.50,
        break_even_trigger=2392.00,
        technical_score=86,
        fundamental_score=62,
        risk_score=78,
        final_score=82,
        risk_reward_ratio=1.44,
        status=SignalStatus.BLOCKED_BY_RISK,
        reason="Barrida de liquidez + recuperación + ruptura de estructura; bloqueada por R:R insuficiente.",
        invalidation_rule="Cierre M15 por debajo de 2378.80.",
        ai_explanation="El sistema detectó intención alcista, pero el ratio riesgo/beneficio no alcanza el mínimo de política. Se debe esperar mejor entrada o ampliar objetivo con lógica técnica.",
    ),
    TradingSignal(
        id="sig_eur_001",
        symbol="EUR/USD",
        direction=Direction.SELL,
        timeframe="M15",
        entry_price=1.08420,
        stop_loss=1.08540,
        take_profit_1=1.08230,
        take_profit_2=1.08120,
        break_even_trigger=1.08230,
        technical_score=81,
        fundamental_score=65,
        risk_score=83,
        final_score=78,
        risk_reward_ratio=1.58,
        status=SignalStatus.ACTIVE,
        reason="Rechazo en resistencia H1 + ruptura de estructura M15 + momentum bajista.",
        invalidation_rule="Cierre M15 por encima de 1.08540.",
        ai_explanation="La señal bajista se sostiene por rechazo en zona de oferta y pérdida de estructura. La entrada debe respetar SL y solo se prepara en demo con confirmación manual.",
    ),
    TradingSignal(
        id="sig_gbp_001",
        symbol="GBP/USD",
        direction=Direction.WAIT,
        timeframe="M15",
        entry_price=None,
        stop_loss=None,
        take_profit_1=None,
        technical_score=48,
        fundamental_score=55,
        risk_score=70,
        final_score=52,
        risk_reward_ratio=None,
        status=SignalStatus.WATCHING,
        reason="Mercado lateral sin confirmación clara.",
        invalidation_rule="Esperar ruptura y retesteo.",
        ai_explanation="No hay ventaja técnica suficiente. El sistema recomienda esperar.",
    ),
]

MOCK_ANALYSES = {
    "XAU/USD": MarketAnalysis(
        symbol="XAU/USD",
        timeframe="M15",
        trend="BULLISH",
        market_structure="BOS",
        liquidity_sweep=True,
        support_resistance_quality=80,
        price_action_quality=84,
        indicator_agreement=72,
        macro_risk="MEDIUM",
        summary="Oro mantiene sesgo alcista intradía, pero la señal requiere mejor relación riesgo/beneficio.",
        confidence=78,
    ),
    "EUR/USD": MarketAnalysis(
        symbol="EUR/USD",
        timeframe="M15",
        trend="BEARISH",
        market_structure="BOS",
        liquidity_sweep=False,
        support_resistance_quality=82,
        price_action_quality=79,
        indicator_agreement=75,
        macro_risk="LOW",
        summary="EUR/USD muestra rechazo en resistencia con estructura bajista confirmada.",
        confidence=76,
    ),
    "GBP/USD": MarketAnalysis(
        symbol="GBP/USD",
        timeframe="M15",
        trend="RANGE",
        market_structure="SIDEWAYS",
        liquidity_sweep=False,
        support_resistance_quality=55,
        price_action_quality=42,
        indicator_agreement=48,
        macro_risk="MEDIUM",
        summary="GBP/USD no ofrece confirmación suficiente. Mejor esperar.",
        confidence=49,
    ),
}
